# Generated by Django 3.2.4 on 2021-07-28 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0003_alter_idea_categ'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='idea',
            options={},
        ),
    ]
