# Generated by Django 3.2.4 on 2021-09-08 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_auto_20210908_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='deleted_content',
            field=models.TextField(blank=True, default=''),
        ),
    ]
